@host=http://localhost:5293
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkNzNlNWNjMS0zNTZmLTQxZmYtODZjZi1hMTkzN2QxZWI4YmEiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFudGliYW5kIiwianRpIjoiM2ZmMGI1OGItMmE5ZS00ZjllLThmYmUtZjZmMGU3MDVlN2IyIiwiZXhwIjoxNzAxOTU4NjU3LCJpc3MiOiJCdWJlckRpbmVyIiwiYXVkIjoiQnViZXJEaW5lciJ9.dpddRLTruh0tpgy9BQVBtmlUjgu3P4NJ4BnYtqjSghk
GET {{host}}/dinners

Authorization: Bearer {{token}}
